name: Publicar Imagen en Docker Hub

on:
  push:
    branches: [ "main" ]
    # El flujo solo se activa si cambia el Dockerfile
    paths:
      - 'Dockerfile'

jobs:
  push_to_registry:
    name: Build y Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v4

      # 1. Login en Docker Hub usando los Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2. Construir la imagen y subirla (Push)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Reemplaza 'tu-usuario' por tu nombre de Docker Hub o usa la variable
          tags: ${{ secrets.DOCKER_USERNAME }}/mi-app-python:latest
